POST http://localhost:9328/V5/StudentNames/Insert/AsIsNoPk
Content-Type: application/json

{
  "StudentName": "",
  "Mobile": "",
  "Email": "",
  "CollegeName": "",
  "Country": "",
  "EntranceRank": "",
  "YearPassOut": "",
  "Back_logs": "",
  "RollNumber": "",
  "file": "",
  "GitLink": "",
  "Intern2025": "",
  "isEmailVerified": "",
  "gpsLat": "",
  "gpsLng": "",
  "gpsAccuracy": ""
}
