POST http://localhost:3000/V1/StudentNames/InsertWithChecks/ForUnique
Content-Type: application/json

{
  "StudentName": "",
  "Mobile": "",
  "Email": "",
  "CollegeName": "",
  "Country": "",
  "EntranceRank": "",
  "YearPassOut": "",
  "Back_logs": "",
  "RollNumber": "",
  "file": "",
  "GitLink": "",
  "Intern2025": ""
}
